stages:
  load_data:
    cmd: python src/stage_01.py --config=config/config.yaml
    deps:
      - src/stage_01.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  preprocess_data:
    cmd: python src/stage_02.py
    deps:
      - src/stage_02.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
  train_model:
    cmd: python src/stage_03.py
    deps:
      - src/stage_03.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
      - params.yaml
    outs:
      - artifacts/model_dir/model.pkl
    
  evaluate:
    cmd: python src/stage_04.py
    deps:
      - src/stage_04.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/model.pkl
    outs:
      - artifacts/report_dir/report.json