stages:
  load_data:
    cmd: python src/stage_01.py --config=config/config.yaml
    deps:
      - src/stage_01.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  preprocess_data:
    cmd: python src/stage_02.py
    deps:
      - src/stage_02.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/raw_local_dir/data.csv
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv