data_source: "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

artifacts:
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv
  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv
  model_dir: model_dir
  model_path: model.pkl
  report_dir: report_dir
  report: report.json